name: run-bot
on: [push]
jobs:
  run-and-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: pip install -r requirements.txt
      - run: python3 main.py 
    